version: "3.8"

services:
  web:
    image: registry.gitlab.com/web3205208/tokeninfo/app.web.token.info:master
    # build:
    #   context: .
    #   dockerfile: ./docker/Dockerfile
    container_name: token.info.web.local
    env_file:
      - .env
    ports:
      - 3000:80
    networks:
      - web3

networks:
  web3:
    external: true
