version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: token.info.web.local
    env_file:
      - .env
    ports:
      - 3000:80
    networks:
      - web3

networks:
  web3:
    external: true
