version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: token.info.web.local
    ports:
      - 3000:3000
    networks:
      - web3

networks:
  web3:
    external: true
